name: On Issues Opened
permissions: write-all
on:
  issues:
    types: [opened]

jobs:
  summarize_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
          run: |
            echo "hello world" > hello.txt
            cat hello.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            - hello.txt
