name: On Issues Opened
permissions: write-all
on:
  issues:
    types: [opened]

jobs:
  summarize_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create file
        run: |
          echo hello > hello.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            - hello.txt
