name: On Issues Opened
permissions: write-all
on:
  issues:
    types: [opened]

jobs:
  summarize_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            ${{github.event.issue.title}}
            ${{github.event.issue.body}}
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
